### ISSUE TITLE
Error: Webserver(SSL)

### ISSUE THREAD

**Issue by Eulerianial** [joshuacox/local-debian#1]
I deployed the domoticz image for arm on Rpi-3 model B using resinOS. After deploying I am hitting following error:

Error: WebServer(SSL) startup failed on
 address 0.0.0.0 with port: 443: use_certificate_chain_file: No such file or directory.

The complete log is as follows:
05.07.17 23:57:15 (+0200) 2017-07-05 16:57:15.777  Domoticz V3.6959 (c)2012-2017 GizMoCuz
05.07.17 23:57:15 (+0200) 2017-07-05 16:57:15.777  Build Hash: 16cba568-modified, Date: 20
17-03-15 06:21:36
05.07.17 23:57:15 (+0200) 2017-07-05 16:57:15.778  System: Raspberry Pi
05.07.17 23:57:15 (+0200) 2017-07-05 16:57:15.778  Startup Path: /src/domoticz/
05.07.17 23:57:16 (+0200) 2017-07-05 16:57:16.415  PluginSystem: Started, Python version '
3.5.3'.
05.07.17 23:57:16 (+0200) 2017-07-05 16:57:16.421  Active notification Subsystems: gcm, ht
tp (2/12)
05.07.17 23:57:16 (+0200) 2017-07-05 16:57:16.445  WebServer(HTTP) started on address: ::
with port 8080
05.07.17 23:57:16 (+0200) 2017-07-05 16:57:16.471  Error: WebServer(SSL) startup failed on
 address 0.0.0.0 with port: 443: use_certificate_chain_file: No such file or directory
05.07.17 23:57:16 (+0200) 2017-07-05 16:57:16.471  Error: WebServer(SSL) check privileges
for opening ports below 1024
05.07.17 23:57:16 (+0200) 2017-07-05 16:57:16.472  Proxymanager started.
05.07.17 23:57:16 (+0200) 2017-07-05 16:57:16.474  Starting shared server on: :::6144
05.07.17 23:57:16 (+0200) 2017-07-05 16:57:16.474  TCPServer: shared server started...
05.07.17 23:57:16 (+0200) 2017-07-05 16:57:16.475  RxQueue: queue worker started...
06.07.17 14:51:07 (+0200) 2017-07-06 07:51:07.000  EventSystem: reset all events...
06.07.17 14:51:07 (+0200) 2017-07-06 07:51:07.001  EventSystem: reset all device statuses.
..
06.07.17 14:51:07 (+0200) 2017-07-06 07:51:07.002  EventSystem: Started
06.07.17 14:51:07 (+0200) 2017-07-06 07:51:07.499  PluginSystem: Entering work loop.

I only deployed the image on resinOS and application started by itself.

**Comment by joshuacox** [comment]
sorry I have been needing to recompile the arm image for awhile now, I'll get to that right now

**Comment by joshuacox** [comment]
pushing the latest compile up now.  Please re-open this issue if you have further difficulties
